name = "pokemon-board-mp"
main = "src/index.js"
compatibility_date = "2025-01-15"

[[durable_objects.bindings]]
name = "ROOMS"
class_name = "GameRoom"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["GameRoom"]
